import {useEffect,useRef,useState} from 'react';
import {Film} from 'lucide-react';
import {animationStyle} from '../engine/animation';
export default function VideoPreview({scenes,settings,selectedId,onSelect,music}){const [playing,setPlaying]=useState(false); const [time,setTime]=useState(0); const audioRef=useRef(null); const musicRef=useRef(null); const startRef=useRef(0); const raf=useRef(); const total=scenes.reduce((a,s)=>a+s.duration,0); const currentIndex=(()=>{let x=0;for(let i=0;i<scenes.length;i++){if(time<x+scenes[i].duration)return i;x+=scenes[i].duration}return Math.max(0,scenes.length-1)})(); const scene=scenes[currentIndex]; let before=0; for(let i=0;i<currentIndex;i++)before+=scenes[i].duration; const progress=scene?Math.min(1,Math.max(0,(time-before)/scene.duration)):0;
 useEffect(()=>{if(!playing){cancelAnimationFrame(raf.current);return} startRef.current=performance.now()-time*1000; const tick=now=>{const t=(now-startRef.current)/1000;if(t>=total){setTime(total);setPlaying(false);return} setTime(t);raf.current=requestAnimationFrame(tick)};raf.current=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf.current)},[playing,total]);
 useEffect(()=>{if(!playing)return; if(musicRef.current)musicRef.current.pause(); if(music?.file){const m=new Audio(music.file);m.loop=music.loop!==false;m.volume=music.volume??.15;m.currentTime=time;m.play().catch(()=>{});musicRef.current=m} return()=>{if(musicRef.current)musicRef.current.pause()}},[playing]);
 useEffect(()=>{if(!scene||!playing)return; if(audioRef.current)audioRef.current.pause(); if(scene.voice){const a=new Audio(scene.voice);a.volume=scene.volume;a.currentTime=Math.max(0,time-before);a.play().catch(()=>{});audioRef.current=a;return()=>a.pause()}},[currentIndex,playing]);
 const toggle=()=>{if(!scenes.length)return;if(time>=total)setTime(0);setPlaying(v=>!v)};
 return <section className="preview-area"><div className="preview-toolbar"><span>Preview</span><div><button className="mini" onClick={toggle}>{playing?'Pause':'Play'}</button><span className="timecode">{time.toFixed(1)} / {total.toFixed(1)}s</span></div></div><div className={`canvas ${settings.aspect==='9:16'?'vertical':''}`} style={{aspectRatio:settings.aspect==='9:16'?'9/16':'16/9'}} onClick={()=>scene&&onSelect(scene.id)}>{scene?.image?<><img className="preview-image" src={scene.image} style={animationStyle(scene,progress)} alt=""/>{scene.dialogue&&<div className={`subtitle ${scene.subtitle.position}`} style={{fontSize:`${scene.subtitle.fontSize}px`}}><span className={scene.subtitle.background?'boxed':''}>{scene.dialogue}</span></div>}</>:<div className="empty-preview"><Film size={42}/><p>Add images to start your anime video</p></div>}<div className="safe-frame"/></div><div className="preview-hint">{settings.width} × {settings.height} • {settings.fps} FPS • {settings.aspect}</div></section>}
